services:
  stockfish:
    image: ivangabriele/stockfish:15
    container_name: stockfish_container
    environment:
      # - API_TOKEN=REPLACE_THIS_TOKEN_BY_A_SECURE_ONE
      - DOMAIN=*
      - PORT=4000
    ports:
      - '4000:4000'
